name: Deploy Images to dockerhub
on:
  push:
    branches:
      - deploy
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile pdd_api
      working-directory: pdd_api
      run: tsc-p . 
    - name: Docker Login
      working-directory: pdd_api
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u DOCKER_USER -P DOCKER_PASSWORD
    - name: Building the pdd_api image
      working-directory: pdd_api
      run: docker build . --tag ${{ secrets.DOCKER_USER }}/pdd_api
    - name: Pushing image to registry
      run: docker push ${{ secrets.DOCKER_USER }}
